# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
# - task: AzureCLI@2
#   displayName: Azure CLI
#   inputs:
#     azureSubscription: $(AZCONNECTION)
#     scriptType: pscore
#     scriptLocation: inlineScript
#     inlineScript: |
#       az --version
#       az account show
#       az login

- task: DownloadSecureFile@1
  name: sshCert1
  inputs:
    secureFile: 'id_rsa'

- task: DownloadSecureFile@1
  name: sshCert2
  inputs:
    secureFile: 'id_rsa.pub'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       # Write your commands here
#       TEST_SSH_KEY_PATH=$(System.DefaultWorkingDirectory)

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $TEST_SSH_KEY_PATH
  env: 
   TEST_SSH_KEY_PATH: $(sshCert1.secureFilePath)
   ARM_CLIENT_ID: $(PrincipalClientId)
   ARM_CLIENT_SECRET: $(PrincipalSecret)
   ARM_SUBSCRIPTION_ID: $(PrincipalSubscription)
   ARM_TENANT_ID: $(PrincipalTenant)
  displayName: set enviroment variable

- bash: |
        # Use curl to download the binary
        curl --location --silent --fail --show-error -o terratest_log_parser https://github.com/gruntwork-io/terratest/releases/download/v0.13.13/terratest_log_parser_linux_amd64
        # Make the downloaded binary executable
        chmod +x terratest_log_parser
        # Finally, we place the downloaded binary to a place in the PATH
        sudo mv terratest_log_parser /usr/local/bin
        # Display go version

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #echo variable
      export TEST_SSH_KEY_PATH=/home/vsts/work/_temp/
      export ARM_CLIENT_ID=$(PrincipalClientId)
      export ARM_CLIENT_SECRET=$(PrincipalSecret)
      export ARM_SUBSCRIPTION_ID=$(PrincipalSubscription)
      export ARM_TENANT_ID=$(PrincipalTenant)
      env
      #list files
      ls $TEST_SSH_KEY_PATH

  displayName: print enviroment variable

# Run Terratest
- bash: |
        cd $(System.DefaultWorkingDirectory)/src/test
        go mod init NEC-MPC-Team/DevOpsPOC-E2ETest
        go test -v -timeout 30m | tee test_output.log
        terratest_log_parser -testlog test_output.log -outputdir test_output

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
